namespace: kubealex
name: general
version: 1.0.0
readme: README.md
authors:
  - Alessandro Rossi <al.rossi87@gmail.com>
description: The purpose of this collection is to group some useful roles and modules that I created during time.
license:
  - Apache-2.0


# A list of tags you want to associate with the collection for indexing/searching. A tag name has the same character
# requirements as 'namespace' and 'name'
tags: []

dependencies: {}

# The URL of the originating SCM repository
repository: https://github.com/kubealex/kubealex.general

# The URL to any online docs
documentation: https://github.com/kubealex/kubealex.general/blob/main/README.md

homepage: https://github.com/kubealex/kubealex.general
issues: https://github.com/kubealex/kubealex.general/issues
build_ignore: []
